spring:
  application:
    name: sparktech-property-access-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: qa  

server:
  port: ${port:8100}
  
  
management:
  endpoints:
    web:
      exposure:
        include: health